### ISSUE TITLE
Translation progress

### ISSUE THREAD

**Issue by webknjaz** [open-craft-guild/open-source-guide#4]
This is a meta-ticket for tracking the overall progress. Please declare your intention to translate certain article before you proceed in order to avoid race conditions :)
If you are not in the @open-craft-guild/translators team, please file an issue listing your email (for the slack invitation).

**Please note that you should file your PRs against `gh-pages-translations/uk-UA` branch.**

* [ ] common terms dictionary | #{{ fill in }}
* [ ] `_config.yml` | #5 (partially, needs clarification)
* [x] `_data/locale/uk-UA.yml` | #6
* [ ] `_articles/best-practices.md` | #7
* [ ] `_articles/building-community.md` | #8
* [x] `_articles/code-of-conduct.md` | #9
* [ ] `_articles/finding-users.md` | #10
* [ ] `_articles/getting-paid.md` | #11
* [ ] `_articles/how-to-contribute.md` | #12
* [ ] `_articles/leadership-and-governance.md` | #13
* [ ] `_articles/legal.md` | #14
* [ ] `_articles/metrics.md` | #15
* [ ] `_articles/starting-a-project.md` | #16
* [ ] `CNAME` | #{{ fill in }} (it's unclear how to share it w/o conflicts)
